name: Equilibrian
favicon: null
layout_spectrum: 0.8916030949912965
typography_spectrum: 0.11374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#57585a'
    - '#e1e1e1'
    - '#939395'
    - '#161616'
  brandStrength: 0.868641049368307
  lightness: 0.7066652083303779
  saturation: 0.4096259893849492
  rhythmicContrast: 0.6825467604212463
purpose: []
